const AUTH = {
    REGISTER_START: 'AUTH_REGISTER_START',
    REGISTER_ERROR: 'AUTH_REGISTER_ERROR',
    REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',
    SET_REDIRECT_PATH: 'AUTH_SET_REDIRECT_PATH',
    CONFIRM_START: 'AUTH_CONFIRM_START',
    CONFIRM_ERROR: 'AUTH_CONFIRM_ERROR',
    CONFIRM_SUCCESS: 'AUTH_CONFIRM_SUCCESS',
    LOGIN_START: 'AUTH_LOGIN_START',
    LOGIN_ERROR: 'AUTH_LOGIN_ERROR',
    LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
    LOGIN_CHECK_SUCCESS: 'AUTH_LOGIN_CHECK_SUCCESS',
    LOGIN_CHECK_FAIL: 'AUTH_LOGIN_CHECK_FAIL',
    LOGOUT_START: 'AUTH_LOGOUT_START',
    LOGOUT_ERROR: 'AUTH_LOGOUT_ERROR',
    LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',
};

const USER = {
    SET_DATA: 'USER_SET_DATA'
}

export {
    AUTH, USER
};