const AUTH = {
    REGISTER_START: 'AUTH_REGISTER_START',
    REGISTER_ERROR: 'AUTH_REGISTER_ERROR',
    REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',
    SET_REDIRECT_PATH: 'AUTH_SET_REDIRECT_PATH',
    CONFIRM_START: 'AUTH_CONFIRM_START',
    CONFIRM_ERROR: 'AUTH_CONFIRM_ERROR',
    CONFIRM_SUCCESS: 'AUTH_CONFIRM_SUCCESS',
    LOGIN_START: 'AUTH_LOGIN_START',
    LOGIN_ERROR: 'AUTH_LOGIN_ERROR',
    LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
    LOGIN_CHECK_SUCCESS: 'AUTH_LOGIN_CHECK_SUCCESS',
    LOGIN_CHECK_FAIL: 'AUTH_LOGIN_CHECK_FAIL',
    LOGOUT_START: 'AUTH_LOGOUT_START',
    LOGOUT_ERROR: 'AUTH_LOGOUT_ERROR',
    LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',
    FORGOT_START: 'AUTH_FORGOT_START',
    FORGOT_ERROR: 'AUTH_FORGOT_ERROR',
    FORGOT_SUCCESS: 'AUTH_FORGOT_SUCCESS',
    RESET_START: 'AUTH_RESET_START',
    RESET_ERROR: 'AUTH_RESET_ERROR',
    RESET_SUCCESS: 'AUTH_RESET_SUCCESS',
};

const USER = {
    SET_DATA: 'USER_SET_DATA',
    GET_PROFILE_START: 'USER_GET_PROFILE_START',
    GET_PROFILE_ERROR: 'USER_GET_PROFILE_ERROR',
    GET_PROFILE_SUCCESS: 'USER_GET_PROFILE_SUCCESS',
    POST_PROFILE_START: 'USER_POST_PROFILE_START',
    POST_PROFILE_ERROR: 'USER_POST_PROFILE_ERROR',
    POST_PROFILE_SUCCESS: 'USER_POST_PROFILE_SUCCESS'
}

export {
    AUTH, USER
};